"""empty message

Revision ID: 25251dda3038
Revises: c9fb3426eea1
Create Date: 2018-01-22 21:34:28.760204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25251dda3038'
down_revision = 'c9fb3426eea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manotes_notes', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manotes_notes', 'color')
    # ### end Alembic commands ###
