"""empty message

Revision ID: 37095c73358e
Revises: 54b51507285e
Create Date: 2018-07-29 16:50:39.365124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37095c73358e'
down_revision = '54b51507285e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manotes_notes', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('manotes_notes', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('manotes_users', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('manotes_users', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manotes_users', 'update_date')
    op.drop_column('manotes_users', 'creation_date')
    op.drop_column('manotes_notes', 'update_date')
    op.drop_column('manotes_notes', 'creation_date')
    # ### end Alembic commands ###
