"""empty message

Revision ID: 4b6fea9af9dd
Revises: 37095c73358e
Create Date: 2018-08-05 19:37:43.504008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6fea9af9dd'
down_revision = '37095c73358e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manotes_users', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manotes_users', 'avatar_path')
    # ### end Alembic commands ###
