"""empty message

Revision ID: c15ab660f057
Revises: 6369939934f2
Create Date: 2018-07-07 17:32:50.180715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15ab660f057'
down_revision = '6369939934f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manotes_notes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'manotes_notes', 'manotes_user', ['user_id'], ['id'])
    op.drop_constraint(u'manotes_user_token_key', 'manotes_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'manotes_user_token_key', 'manotes_user', ['token'])
    op.drop_constraint(None, 'manotes_notes', type_='foreignkey')
    op.drop_column('manotes_notes', 'user_id')
    # ### end Alembic commands ###
