"""empty message

Revision ID: c9fb3426eea1
Revises: 7e71fa7558cf
Create Date: 2018-01-22 21:32:46.812852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb3426eea1'
down_revision = '7e71fa7558cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
